---
name: Automerge
on:
  workflow_call:
    secrets:
      token:
        required: true
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Check allowed files
        run: |
          find . -type f ! -name 'go.mod' ! -name 'go.sum' ! -name '*.yaml' ! -name '*.yml' ! -name '*.txt' ! -name '*.md' ! -name '*.conf' ! -name 'Dockerfile' -exec git diff --exit-code origin/main -- {} +

      - name: Merge PR
        run: |
          gh pr merge ${{ github.event.workflow_run.head_branch }} --squash --delete-branch
        env:
          GH_TOKEN: ${{ secrets.token }}

