---
name: Check mergeability
on:
  workflow_call:
    secrets:
      token:
        required: true
    outputs:
      pr_number:
        value: ${{ jobs.check_mergeability.outputs.pr_number }}
jobs:
  check_mergeability:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.validate_pr.outputs.pr_number }}
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Check PR
        id: check_pr
        run: |
          pr_info=$(gh pr list --head ${{ github.event.workflow_run.head_branch }} --json number,mergeable)
          pr_number=$(echo $pr_info | jq -r '.[0].number')
          mergeable=$(echo $pr_info | jq -r '.[0].mergeable')

          if [ "$pr_number" == "null" ]; then
            echo "No opened PR was found for branch ${{ github.event.workflow_run.head_branch }}"
            exit 1
          fi
          echo "pr_number=$pr_number" >> $GITHUB_OUTPUT

          if [ "$mergeable" != "MERGEABLE" ]; then
            echo "PR $pr_number has conflicts"
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

