---
name: Check mergeability
on:
  workflow_call:
    secrets:
      token:
        required: true
    outputs:
      pr_number:
        value: ${{ jobs.check_mergeability.outputs.pr_number }}
      mergeable:
        value: ${{ jobs.check_mergeability.outputs.mergeable }}
jobs:
  check_mergeability:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.validate_pr.outputs.pr_number }}
      mergeable: ${{ steps.validate_pr.outputs.mergeable }}
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Check PR
        id: check_pr
        run: |
          pr_info=$(gh pr list --head ${{ github.event.workflow_run.head_branch }} --json number,mergeable)

          echo pr_info: $pr_info
          pr_number=$(echo $pr_info | jq '.[0].number')
          mergeable=$(echo $pr_info | jq '.[0].mergeable')

          if [ -z "$pr_number" ]; then
            echo "No opened PR was found for branch ${{ github.event.workflow_run.head_branch }}"
            exit 1
          fi
          echo "pr_number=$pr" >> $GITHUB_OUTPUT

          if [ "$mergeable" != "MERGEABLE" ]; then
            echo "mergeable=false" >> $GITHUB_OUTPUT
            echo "PR $pr_number has conflicts"
            exit 1
          fi
          echo "mergeable=true" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

