---
name: Check mergeability
on:
  workflow_call:
    secrets:
      token:
        required: true
jobs:
  check_mergeability:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Check PR
        id: check_pr
        run: |
          pr_info=$(gh pr list --head ${{ github.event.workflow_run.head_branch }} --json number,mergeable)
          pr_number=$(echo $pr_info | jq -r '.[0].number')
          mergeable=$(echo $pr_info | jq -r '.[0].mergeable')

          if [ "$pr_number" == "null" ]; then
            echo "No opened PR was found for branch ${{ github.event.workflow_run.head_branch }}"
            exit 1
          fi

          if [ "$mergeable" != "MERGEABLE" ]; then
            echo "mergeable=false" >> $GITHUB_OUTPUT
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

