---
name: Check generated files
on:
  workflow_call:
jobs:
  gogenerate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          15.15.15
      - run: go generate ./...
      - name: Check for changes
        run: |
          git diff --name-only --exit-code || ( echo "Rerun go generate ./... locally and resubmit" && false )
