---
name: Docker Build & test
on:
  workflow_call:
    secrets:
      token:
        required: true
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.19.12
      - name: Build container
        run: docker build .
      - name: Run tests
        run: docker run --privileged --rm $(docker build -q . --target test)
