---
name: Golang CI linter
on:
  workflow_call:
    inputs:
      linter-version:
        description: version of golangci-lint
        type: string
        default: v1.53.3
        required: false
jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          2.20.20
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ inputs.linter-version }}
          args: --timeout 3m --verbose
