---
name: Update Go in all NSM repos
run-name: ${{ github.actor }} has started updating Go version in all NSM repos
on:
  push:
    branches:
      - 'main'
jobs:
  fetch-repositories:
    name: Fetch organization repositories
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.push.head_commit.message, 'update/go_')}}
    outputs:
      repositories: ${{ steps.organization-repositories.outputs.repositories }}
    steps:
      - name: Run `get-organization-repositories`
        id: organization-repositories
        uses: denis-tingajkin/get-organization-repositories@v1.0.1
        with:
          github-organization: 'NikitaSkrynnik'

  update-all-repos:
    runs-on: ubuntu-latest
    needs: fetch-repositories
    strategy:
      matrix:
        repository: ${{ fromJSON(needs.fetch-repositories.outputs.repositories) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: ${{ matrix.repository }}
          repository: ${{ matrix.repository }}
          token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}

      - name: Get a new Go version
        id: get-go-version
        run: |
            NEW_GO_VERSION=$(echo "${{ github.event.push.head_commit.message }}" | grep -o "[0-9]\+.[0-9]\+.[0-9]\+")
            NEW_GO_MAJOR_VERSION=${NEW_GO_VERSION%.*}

            echo "New go version $NEW_GO_VERSION"
            echo "New go major version $NEW_GO_MAJOR_VERSION"

            echo "new-go-version=${NEW_GO_VERSION}" >> "$GITHUB_OUTPUT"
            echo "new-go-major-version=${NEW_GO_MAJOR_VERSION}" >> "$GITHUB_OUTPUT"

      - name: Update Go version in code to ${{ steps.get-version-number.outputs.new-go-version }}
        run: |
          find .github/workflows -name '*.yaml' -exec sed -i -e 's/go-version\: [0-9]\+\.[0-9]\+\.[0-9]\+/${{steps.get-go-version.outputs.new-go-version}}/g' {} +;
          find .github/workflows -name '*.yaml' -exec sed -i -e 's/go-version\: [0-9]\+\.[0-9]\+\.[0-9]\+/${{steps.get-go-version.outputs.new-go-version}}/g' {} +;

      - name: Create & push commit
        run: |
          git config --global user.email "nikita.skrynnik@xored.com"
          git config --global user.name "NikitaSkrynnik"
          git commit -s -a -m "Update Go version to ${{ steps.get-version-number.outputs.new-go-version }}"
          git push

  create-pull-request:
    uses: NikitaSkrynnik/.github/.github/workflows/pr-for-updates.yaml@main
    needs: [update-go-version]
    secrets:
      token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}
