---
name: Update Golang version
run-name: ${{ github.actor }} has started Golang version update
on:
  push:
    branches:
      - 'update/go_*'
jobs:
  update-go-version:
    runs-on: ubuntu-latest
    outputs:
      new-go-version: ${{ steps.get-version-number.outputs.new-go-version }}
      new-go-major-version: ${{ steps.get-version-number.outputs.new-go-major-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get old and new go versions
        id: get-go-version
        run: |
            OLD_GO_VERSION=$(grep -F "go-version: " .github/workflows/build-and-test.yaml)
            OLD_GO_VERSION=${OLD_GO_VERSION//"go-version: "/""}
            OLD_GO_MAJOR_VERSION=${OLD_GO_VERSION%.*}

            NEW_GO_VERSION=${${{ github.ref }}//"refs/heads/update/go_"/""}
            NEW_GO_MAJOR_VERSION=${NEW_GO_VERSION%.*}

            echo "Old go version $OLD_GO_VERSION"
            echo "Old go major version $OLD_GO_MAJOR_VERSION"

            echo "New go version $NEW_GO_VERSION"
            echo "New go major version $NEW_GO_MAJOR_VERSION"

            echo "old-go-version=${OLD_GO_VERSION}" >> "$GITHUB_OUTPUT"
            echo "old-go-major-version=${OLD_GO_MAJOR_VERSION}" >> "$GITHUB_OUTPUT"

            echo "new-go-version=${NEW_GO_VERSION}" >> "$GITHUB_OUTPUT"
            echo "new-go-major-version=${NEW_GO_MAJOR_VERSION}" >> "$GITHUB_OUTPUT"

      - name: Update Go version in code to ${{ steps.get-version-number.outputs.new-go-version }}
        run: |
          find . -name '*.yaml' -exec sed -i -e 's/${{steps.get-go-version.outputs.old-go-version}}/${{steps.get-go-version.outputs.new-go-version}}/g' {} +;
          find . -name '*.yaml' -exec sed -i -e 's/${{steps.get-go-version.outputs.old-go-major-version}}/${{steps.get-go-version.outputs.new-go-major-version}}/g' {} +;
      
      - name: Create & push commit
        run: |
          git config --global user.email "nsmbot@networkservicmesh.io"
          git config --global user.name "NSMBot"
          git commit -s -a -m "Update Go version to ${{ steps.get-version-number.outputs.new-go-version }}"
          git push
